import { NextResponse } from 'next/server';

export async function GET(req: Request) {
    const { searchParams } = new URL(req.url);
    const projectId = searchParams.get('projectId') || '';
    
    // Core Auth JS Library dynamically served
    const authJsCode = `
// @ts-nocheck
/**
 * PostPipe Authentication Client
 * Auto-generated by PostPipe Dashboard
 */

(function (global) {
    class PostpipeAuthClient {
        constructor() {
            this.config = {
                projectId: null,
                providers: ['email'],
                redirectUrl: window.location.origin,
                envFrontendUrlAlias: null,
                projectAlias: null,
                apiUrl: 'http://localhost:3002/api/auth'
            };
            this.listeners = {
                success: [],
                error: []
            };
            this.isInitialized = false;
            this._mode = 'login';
            this._pendingEmail = '';
            this._token = null;
            this._isRegisterMode = false;
            this._isForgotPasswordMode = false;
        }

        init(userConfig) {
            this.config = { ...this.config, ...userConfig };
            this.isInitialized = true;
            
            // Recovery token from config or storage
            this._token = this.config.token || localStorage.getItem(\`pp_auth_\${this.config.projectId}\`);

            // Check for Landing Page states
            const params = new URLSearchParams(window.location.search);
            this._ppAction = params.get('pp_action');
            this._ppToken = params.get('token');

            this.injectStyles();
            this.checkOAuthCallback();
            
            // If we have a token, auto-introspect
            if (this._token) {
                this.me();
            }

            // Always try to render if an action is present
            this.render();
        }

        on(event, callback) {
            if (this.listeners[event]) {
                this.listeners[event].push(callback);
            }
        }

        emit(event, data) {
            if (this.listeners[event]) {
                this.listeners[event].forEach(cb => cb(data));
            }
        }

        async loginWithEmail(email, password) {
            try {
                this.setLoading(true);
                const response = await fetch(\`\${this.config.apiUrl}/login\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        email, password, 
                        projectId: this.config.projectId, 
                        targetDatabase: this.config.targetDatabase,
                        redirectUrl: this.config.redirectUrl,
                        envFrontendUrlAlias: this.config.envFrontendUrlAlias,
                        projectAlias: this.config.projectAlias
                    })
                });

                const data = await response.json();
                
                if (response.status === 403 && data.requiresOtp) {
                    this._pendingEmail = email;
                    this._mode = 'otp';
                    this.render();
                    return;
                }

                if (!response.ok) throw new Error(data.message || 'Login failed');
                
                this.emit('success', data.user);
                this.setAuthToken(data.token);
                this.handleRedirect();
            } catch (err) {
                this.showError(err.message);
                this.emit('error', err);
            } finally {
                this.setLoading(false);
            }
        }

        async registerWithEmail(name, email, password) {
            try {
                this.setLoading(true);
                const response = await fetch(\`\${this.config.apiUrl}/register\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        name, email, password, 
                        projectId: this.config.projectId, 
                        targetDatabase: this.config.targetDatabase,
                        redirectUrl: this.config.redirectUrl,
                        envFrontendUrlAlias: this.config.envFrontendUrlAlias,
                        projectAlias: this.config.projectAlias
                    })
                });

                const data = await response.json();

                if (response.status === 201 && data.requiresOtp) {
                    this._pendingEmail = email;
                    this._mode = 'otp';
                    this.render();
                    return;
                }

                if (!response.ok) throw new Error(data.message || 'Registration failed');
                
                this.showSuccess(data.message || 'Success! Check your email.');
                this.emit('success', data.user);
            } catch (err) {
                this.showError(err.message);
                this.emit('error', err);
            } finally {
                this.setLoading(false);
            }
        }

        async resetPassword(newPassword) {
            try {
                this.setLoading(true);
                const response = await fetch(\`\${this.config.apiUrl}/reset-password\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        token: this._ppToken,
                        newPassword,
                        targetDatabase: this.config.targetDatabase,
                        envFrontendUrlAlias: this.config.envFrontendUrlAlias,
                        projectAlias: this.config.projectAlias
                    })
                });

                const data = await response.json();
                if (!response.ok) throw new Error(data.message || 'Reset failed');
                
                this._ppAction = 'reset-success';
                this.render();
            } catch (err) {
                this.showError(err.message);
                this.emit('error', err);
            } finally {
                this.setLoading(false);
            }
        }

        async verifyEmail() {
            try {
                const response = await fetch(\`\${this.config.apiUrl}/verify-email\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        token: this._ppToken,
                        targetDatabase: this.config.targetDatabase,
                        envFrontendUrlAlias: this.config.envFrontendUrlAlias,
                        projectAlias: this.config.projectAlias
                    })
                });

                const data = await response.json();
                if (!response.ok) throw new Error(data.message || 'Verification failed');
                
                this._ppAction = 'verify-success';
                this.render();
            } catch (err) {
                this._ppAction = 'verify-error';
                this._errorMsg = err.message;
                this.render();
            }
        }

        async me() {
            if (!this._token) return null;
            try {
                const response = await fetch(\`\${this.config.apiUrl}/me?targetDatabase=\${this.config.targetDatabase || ''}\`, {
                    headers: { 'Authorization': \`Bearer \${this._token}\` }
                });
                if (!response.ok) throw new Error('Session expired');
                const user = await response.json();
                this.emit('success', user);
                return user;
            } catch (err) {
                console.warn('[PostpipeAuth] Session introspection failed:', err.message);
                this._token = null;
                return null;
            }
        }

        async verifyOtp() {
            const otp = document.getElementById('pp-otp')?.value;
            if (!otp || otp.length !== 6) return this.showError('Enter a valid 6-digit code.');

            try {
                this.setLoading(true);
                const response = await fetch(\`\${this.config.apiUrl}/verify-otp\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        email: this._pendingEmail, 
                        otp, 
                        targetDatabase: this.config.targetDatabase,
                        envFrontendUrlAlias: this.config.envFrontendUrlAlias,
                        projectAlias: this.config.projectAlias
                    })
                });

                const data = await response.json();
                if (!response.ok) throw new Error(data.message || 'Verification failed');

                this.setAuthToken(data.token);
                this.emit('success', data.user);
                this.handleRedirect();
                
                this._mode = 'login';
                this.showSuccess('Email verified successfully! You can now sign in.');
                this.render();
            } catch (err) {
                this.showError(err.message);
            } finally {
                this.setLoading(false);
            }
        }

        async resendOtp() {
            try {
                this.setLoading(true);
                const response = await fetch(\`\${this.config.apiUrl}/resend-otp\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        email: this._pendingEmail, 
                        targetDatabase: this.config.targetDatabase,
                        envFrontendUrlAlias: this.config.envFrontendUrlAlias,
                        projectAlias: this.config.projectAlias
                    })
                });

                const data = await response.json();
                if (!response.ok) throw new Error(data.message || 'Failed to resend');
                this.showSuccess('New code sent to your email!');
            } catch (err) {
                this.showError(err.message);
            } finally {
                this.setLoading(false);
            }
        }

        async forgotPasswordWithEmail(email) {
            try {
                this.setLoading(true);
                const response = await fetch(\`\${this.config.apiUrl}/forgot-password\`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ 
                        email,
                        redirectUrl: this.config.redirectUrl,
                        envFrontendUrlAlias: this.config.envFrontendUrlAlias,
                        projectAlias: this.config.projectAlias
                    })
                });

                const data = await response.json();
                this.showSuccess("If the account exists, a reset link has been sent.");
            } catch (err) {
                this.showError(err.message);
            } finally {
                this.setLoading(false);
            }
        }

        loginWithOAuth(provider) {
            const oauthUrl = \`\${this.config.apiUrl}/\${provider}?projectId=\${this.config.projectId || ''}&targetDatabase=\${this.config.targetDatabase || ''}&envFrontendUrlAlias=\${this.config.envFrontendUrlAlias || ''}&projectAlias=\${this.config.projectAlias || ''}&redirect=\${encodeURIComponent(window.location.href)}\`;
            window.location.href = oauthUrl;
        }

        checkOAuthCallback() {
            const urlParams = new URLSearchParams(window.location.search);
            const token = urlParams.get('pp_token');
            const error = urlParams.get('pp_error');

            if (token) {
                this.setAuthToken(token);
                window.history.replaceState({}, document.title, window.location.pathname);
                try {
                    const payload = JSON.parse(atob(token.split('.')[1]));
                    this.emit('success', payload);
                } catch(e) {}
            } else if (error) {
                this.emit('error', new Error(decodeURIComponent(error)));
                this.showError(decodeURIComponent(error));
            }
        }

        handleRedirect() {
            if (this.config.redirectUrl && this.config.redirectUrl !== 'window.location.origin') {
                window.location.href = this.config.redirectUrl;
            }
        }

        setAuthToken(token) {
            this._token = token;
            localStorage.setItem(\`pp_auth_\${this.config.projectId}\`, token);
        }

        injectStyles() {
            if (document.getElementById('pp-auth-styles')) return;
            const style = document.createElement('style');
            style.id = 'pp-auth-styles';
            style.innerHTML = \`
                @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
                
                .pp-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.4); backdrop-filter: blur(12px); -webkit-backdrop-filter: blur(12px); display: flex; align-items: center; justify-content: center; z-index: 999999; padding: 20px; animation: pp-fade-in 0.3s ease-out; box-sizing: border-box; }
                #postpipe-auth { font-family: 'Inter', system-ui, -apple-system, sans-serif; width: 100%; max-width: 440px; margin: 0 auto; background: #fff; border-radius: 32px; box-shadow: 0 25px 50px -12px rgba(0,0,0,0.15); border: 1px solid rgba(0,0,0,0.05); padding: 40px; position: relative; box-sizing: border-box; }
                #postpipe-auth * { box-sizing: border-box !important; }
                .pp-overlay .pp-card { animation: pp-slide-up 0.4s cubic-bezier(0.16, 1, 0.3, 1); width: 100%; max-width: 440px; display: flex; justify-content: center; }
                .pp-overlay #postpipe-auth { animation: pp-slide-up 0.4s cubic-bezier(0.16, 1, 0.3, 1); }
                
                .pp-title { font-size: 28px; font-weight: 800; text-align: center; margin: 0 0 12px 0; color: #111; letter-spacing: -0.04em; }
                .pp-subtitle { font-size: 15px; text-align: center; color: #666; margin-bottom: 32px; line-height: 1.5; }
                
                .pp-input-group { margin-bottom: 24px; }
                .pp-input-group label { display: block; font-size: 14px; font-weight: 600; color: #333; margin-bottom: 10px; padding-left: 4px; }
                .pp-input { width: 100%; max-width: 100%; box-sizing: border-box; padding: 14px 18px; border: 2px solid #f0f0f0; border-radius: 16px; font-size: 16px; transition: all 0.2s; background: #f9fafb; font-family: inherit; }
                .pp-input:focus { outline: none; border-color: #6366f1; background: #fff; box-shadow: 0 0 0 4px rgba(99, 102, 241, 0.1); }
                
                .pp-btn { width: 100%; max-width: 100%; padding: 14px; border: none; border-radius: 16px; font-size: 16px; font-weight: 700; cursor: pointer; transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1); display: flex; align-items: center; justify-content: center; gap: 10px; font-family: inherit; }
                .pp-btn:disabled { opacity: 0.7; cursor: not-allowed; }
                .pp-btn-primary { background: linear-gradient(135deg, #6366f1 0%, #4f46e5 100%); color: #fff; box-shadow: 0 10px 15px -3px rgba(99, 102, 241, 0.3); }
                .pp-btn-primary:hover:not(:disabled) { transform: translateY(-2px); box-shadow: 0 15px 20px -5px rgba(99, 102, 241, 0.4); }
                .pp-btn-primary:active:not(:disabled) { transform: translateY(0); }
                
                .pp-btn-oauth { background: #fff; color: #1f2937; border: 2px solid #f3f4f6; margin-bottom: 12px; }
                .pp-btn-oauth:hover { background: #f9fafb; border-color: #e5e7eb; }
                
                .pp-divider { display: flex; align-items: center; text-align: center; margin: 28px 0; color: #9ca3af; font-size: 13px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.1em; }
                .pp-divider::before, .pp-divider::after { content: ''; flex: 1; border-bottom: 1px solid #f3f4f6; }
                .pp-divider:not(:empty)::before { margin-right: 1.5em; }
                .pp-divider:not(:empty)::after { margin-left: 1.5em; }
                
                .pp-error, .pp-success { padding: 16px; border-radius: 16px; font-size: 14px; margin-bottom: 24px; font-weight: 600; line-height: 1.4; display: none; text-align: center; border: 1px solid transparent; }
                .pp-error { color: #dc2626; background: #fef2f2; border-color: #fee2e2; }
                .pp-success { color: #16a34a; background: #f0fdf4; border-color: #dcfce7; }
                
                .pp-toggle-mode { text-align: center; font-size: 14px; margin-top: 28px; color: #6b7280; font-weight: 500; }
                .pp-toggle-mode a { color: #4f46e5; text-decoration: none; cursor: pointer; font-weight: 700; transition: color 0.2s; }
                .pp-toggle-mode a:hover { color: #4338ca; }
                
                .pp-spinner { border: 3px solid rgba(255,255,255,0.3); border-radius: 50%; border-top: 3px solid #fff; width: 22px; height: 22px; animation: pp-spin 0.8s linear infinite; }
                .pp-celebration { font-size: 56px; margin-bottom: 24px; filter: drop-shadow(0 10px 15px rgba(0,0,0,0.1)); }
                
                @keyframes pp-spin { to { transform: rotate(360deg); } }
                @keyframes pp-fade-in { from { opacity: 0; } to { opacity: 1; } }
                @keyframes pp-slide-up { from { opacity: 0; transform: translateY(20px) scale(0.98); } to { opacity: 1; transform: translateY(0) scale(1); } }
                
                .pp-loader-container { padding: 40px 0; text-align: center; }
                .pp-gradient-loader { height: 6px; width: 220px; margin: 32px auto; background: #f3f4f6; border-radius: 10px; overflow: hidden; position: relative; }
                .pp-gradient-loader::after { content: ''; position: absolute; left: -50%; top: 0; height: 100%; width: 50%; background: linear-gradient(90deg, transparent, #6366f1, transparent); animation: pp-loading 1.2s infinite ease-in-out; }
                @keyframes pp-loading { from { left: -50%; } to { left: 100%; } }

                .pp-close-overlay { position: absolute; top: 20px; right: 20px; width: 40px; height: 40px; background: #f9fafb; border-radius: 50%; cursor: pointer; border: none; font-size: 20px; display: flex; align-items: center; justify-content: center; color: #9ca3af; transition: all 0.2s; z-index: 10; }
                .pp-close-overlay:hover { background: #f3f4f6; color: #4b5563; }
                
                @media (max-width: 480px) {
                    #postpipe-auth { padding: 24px 16px; border-radius: 24px; width: auto; margin: 0 16px; }
                    .pp-title { font-size: 24px; margin-bottom: 8px; }
                    .pp-subtitle { font-size: 14px; margin-bottom: 24px; }
                    .pp-input { padding: 12px 14px; font-size: 15px; }
                    .pp-btn { padding: 12px 14px; font-size: 15px; }
                    .pp-close-overlay { top: 12px; right: 12px; width: 32px; height: 32px; font-size: 18px; }
                    .pp-celebration { font-size: 48px; }
                }
            \`;
            document.head.appendChild(style);
        }

        setLoading(isLoading) {
            const btn = document.getElementById('pp-submit-btn');
            if (btn) {
                btn.disabled = isLoading;
                const text = this._mode === 'otp' ? 'Verify & Log In' : (this._isRegisterMode ? 'Create Account' : (this._isForgotPasswordMode ? 'Send Reset Link' : 'Log In'));
                btn.innerHTML = isLoading ? '<span class="pp-spinner"></span>' : text;
            }
        }

        showError(msg) {
            const div = document.getElementById('pp-error');
            if (!div) return;
            div.innerText = msg;
            div.style.display = 'block';
            const successDiv = document.getElementById('pp-success');
            if (successDiv) successDiv.style.display = 'none';
        }

        showSuccess(msg) {
            const div = document.getElementById('pp-success');
            if (!div) return;
            div.innerText = msg;
            div.style.display = 'block';
            const errorDiv = document.getElementById('pp-error');
            if (errorDiv) errorDiv.style.display = 'none';
        }

        render() {
            let container = document.getElementById('postpipe-auth');
            const isLandingAction = ['verify-email', 'reset-password', 'verify-success', 'reset-success', 'verify-error'].includes(this._ppAction);

            // AUTO-OVERLAY LOGIC: If action is present but container missing, inject overlay
            if (!container && isLandingAction) {
                const overlay = document.createElement('div');
                overlay.className = 'pp-overlay';
                overlay.id = 'pp-auth-overlay';
                
                const card = document.createElement('div');
                card.className = 'pp-card';
                
                container = document.createElement('div');
                container.id = 'postpipe-auth';
                
                // Add close button for overlay
                const closeBtn = document.createElement('button');
                closeBtn.className = 'pp-close-overlay';
                closeBtn.innerHTML = '×';
                closeBtn.onclick = () => {
                    document.body.removeChild(overlay);
                    this._clearParams();
                };
                
                overlay.appendChild(card);
                card.appendChild(container);
                container.appendChild(closeBtn);
                document.body.appendChild(overlay);
            }

            if (!container) return;

            if (this._ppAction === 'verify-email') {
                this.renderVerifyState(container);
                this.verifyEmail();
                return;
            }

            if (this._ppAction === 'verify-success') {
                this.renderSuccessState(container, "Email Verified!", "Your account is now fully activated.");
                return;
            }

            if (this._ppAction === 'verify-error') {
                this.renderErrorState(container, "Verification Failed", this._errorMsg || "The link is expired or invalid.");
                return;
            }

            if (this._ppAction === 'reset-password') {
                this.renderResetState(container);
                return;
            }

            if (this._ppAction === 'reset-success') {
                this.renderSuccessState(container, "Password Reset!", "You can now log in with your new password.");
                return;
            }

            if (this._mode === 'otp') {
                this.renderOtpForm(container);
                return;
            }

            this.renderAuthForm(container);
        }

        renderOtpForm(container) {
            container.innerHTML = \`
                <h2 class="pp-title">Verify Your Email</h2>
                <p class="pp-subtitle">We've sent a 6-digit code to <strong>\${this._pendingEmail}</strong></p>
                <div id="pp-error" class="pp-error"></div>
                <div id="pp-success" class="pp-success"></div>
                
                <div class="pp-input-group">
                    <label>Verification Code</label>
                    <input type="text" id="pp-otp" class="pp-input" placeholder="000000" maxlength="6" 
                        style="text-align: center; letter-spacing: 0.5em; font-size: 24px; font-weight: 800; color: #4f46e5; background: #f5f3ff; border-color: #c7d2fe" autofocus>
                </div>
                
                <button id="pp-submit-btn" onclick="PostpipeAuth.verifyOtp()" class="pp-btn pp-btn-primary">Verify & Log In</button>
                
                <div class="pp-toggle-mode">
                    Didn't get a code? <a onclick="PostpipeAuth.resendOtp()">Resend Code</a>
                </div>
                <div class="pp-toggle-mode" style="margin-top: 12px">
                    <a onclick="PostpipeAuth._mode = 'login'; PostpipeAuth.render()">Back to Log In</a>
                </div>
            \`;
        }

        renderAuthForm(container) {
            const hasGoogle = this.config.providers.includes('google');
            const hasGithub = this.config.providers.includes('github');
            const hasEmail = this.config.providers.includes('email');

            const title = this._isRegisterMode ? 'Create Account' : (this._isForgotPasswordMode ? 'Reset Password' : 'Welcome Back');
            const subtitle = this._isRegisterMode ? 'Start building something amazing' : (this._isForgotPasswordMode ? 'Enter your email to receive a reset link' : 'Enter your credentials to continue');

            let html = \`
                <h2 class="pp-title">\${title}</h2>
                <p class="pp-subtitle">\${subtitle}</p>
                <div id="pp-error" class="pp-error"></div>
                <div id="pp-success" class="pp-success"></div>
            \`;

            if (!this._isForgotPasswordMode) {
                if (hasGoogle) html += \`<button onclick="PostpipeAuth.loginWithOAuth('google')" class="pp-btn pp-btn-oauth"><svg width="18" height="18" viewBox="0 0 24 24"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg> Continue with Google</button>\`;
                if (hasGithub) html += \`<button onclick="PostpipeAuth.loginWithOAuth('github')" class="pp-btn pp-btn-oauth"><svg width="18" height="18" viewBox="0 0 24 24" fill="#333"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"/></svg> Continue with GitHub</button>\`;
                if ((hasGoogle || hasGithub) && hasEmail) html += \`<div class="pp-divider">or</div>\`;
            }

            if (hasEmail) {
                if (this._isRegisterMode) html += \`<div class="pp-input-group"><label>Name</label><input type="text" id="pp-name" class="pp-input" placeholder="Jane Doe"></div>\`;
                html += \`<div class="pp-input-group"><label>Email</label><input type="email" id="pp-email" class="pp-input" placeholder="name@company.com"></div>\`;
                if (!this._isForgotPasswordMode) {
                    html += \`<div class="pp-input-group"><label style="display:flex; justify-content:space-between">Password \${!this._isRegisterMode ? \`<a onclick="PostpipeAuth._toggleForgot()" style="color:#4f46e5; cursor:pointer; font-weight:600; font-size:12px">Forgot?</a>\` : ''}</label><input type="password" id="pp-password" class="pp-input" placeholder="••••••••"></div>\`;
                }
                const btnText = this._isRegisterMode ? 'Create Account' : (this._isForgotPasswordMode ? 'Send Reset Link' : 'Log In');
                html += \`<button id="pp-submit-btn" onclick="PostpipeAuth._handleSubmit()" class="pp-btn pp-btn-primary">\${btnText}</button>\`;
            }

            html += \`<div class="pp-toggle-mode">\${this._isForgotPasswordMode ? 'Remembered? <a onclick="PostpipeAuth._toggleForgot()">Go back</a>' : (this._isRegisterMode ? 'Already have an account? <a onclick="PostpipeAuth._toggleMode()">Log In</a>' : 'No account? <a onclick="PostpipeAuth._toggleMode()">Sign Up</a>')}</div>\`;
            
            container.innerHTML = html;
        }

        renderVerifyState(container) {
            container.innerHTML = \`
                <div class="pp-loader-container">
                    <h2 class="pp-title">Verifying...</h2>
                    <p class="pp-subtitle">Just a moment while we activate your account</p>
                    <div class="pp-gradient-loader"></div>
                </div>
            \`;
        }

        renderResetState(container) {
            container.innerHTML = \`
                <h2 class="pp-title">New Password</h2>
                <p class="pp-subtitle">Please enter a strong new password</p>
                <div id="pp-error" class="pp-error"></div>
                <div class="pp-input-group">
                    <label>New Password</label>
                    <input type="password" id="pp-password" class="pp-input" placeholder="••••••••">
                </div>
                <div class="pp-input-group">
                    <label>Confirm Password</label>
                    <input type="password" id="pp-confirm" class="pp-input" placeholder="••••••••">
                </div>
                <button id="pp-submit-btn" onclick="PostpipeAuth._handleReset()" class="pp-btn pp-btn-primary">Reset Password</button>
            \`;
        }

        renderSuccessState(container, title, text) {
            container.innerHTML = \`
                <div style="text-align:center">
                    <div class="pp-celebration">🎉</div>
                    <h2 class="pp-title">\${title}</h2>
                    <p class="pp-subtitle">\${text}</p>
                    <button onclick="PostpipeAuth._clearParams()" class="pp-btn pp-btn-primary">Continue to Log In</button>
                </div>
            \`;
        }

        renderErrorState(container, title, text) {
            container.innerHTML = \`
                <div style="text-align:center">
                    <div style="font-size:48px; margin-bottom:20px">❌</div>
                    <h2 class="pp-title">\${title}</h2>
                    <p class="pp-subtitle">\${text}</p>
                    <button onclick="PostpipeAuth._clearParams()" class="pp-btn pp-btn-primary">Go Back</button>
                </div>
            \`;
        }

        _toggleMode() { this._isRegisterMode = !this._isRegisterMode; this._isForgotPasswordMode = false; this.render(); }
        _toggleForgot() { this._isForgotPasswordMode = !this._isForgotPasswordMode; this._isRegisterMode = false; this.render(); }
        _clearParams() { window.history.replaceState({}, document.title, window.location.pathname); this._ppAction = null; this.render(); }

        _handleSubmit() {
            const email = document.getElementById('pp-email')?.value;
            if (this._isForgotPasswordMode) return this.forgotPasswordWithEmail(email);
            const pass = document.getElementById('pp-password')?.value;
            if (this._isRegisterMode) {
                this.registerWithEmail(document.getElementById('pp-name').value, email, pass);
            } else {
                this.loginWithEmail(email, pass);
            }
        }

        _handleReset() {
            const p1 = document.getElementById('pp-password').value;
            const p2 = document.getElementById('pp-confirm').value;
            if (p1 !== p2) return this.showError("Passwords do not match");
            if (p1.length < 6) return this.showError("Min 6 characters required");
            this.resetPassword(p1);
        }
    }

    global.PostpipeAuth = new PostpipeAuthClient();
})(window);
`;

    return new NextResponse(authJsCode, {
        status: 200,
        headers: {
            'Content-Type': 'application/javascript',
            'Cache-Control': 'no-store, no-cache, must-revalidate, proxy-revalidate',
            'Pragma': 'no-cache',
            'Expires': '0'
        }
    });
}
